server:
  port: 8080
  base-url: ${SERVER_BASE_URL:http://localhost:8080}
  forward-headers-strategy: native

spring:
  application:
    name: chzzk-favorite-bot

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true

  datasource:
    url: ENC(aaC2l5twFy36wicAJjFw6dNdgEJUGs6HNHcK9z1YRGV8rRnyjchggGCHwOYJAAWrk/F6SvrUzWvx/DCcp8gJKgooROKrI2fCXWEWNu5x1GM=)
    username: ENC(8rEbRK5wP4t3G/5uvMuxpYFpjNvQdCszFCB5O47VpKpgMkkZNUMMb98acnZIlPye)
    password: ENC(E5g3c0TOyhN1ziHJZA1czIyNuz6bVnQZsxQhoAdLOIkbXcoYaucWIxr4YIiG+iUfnw6ctMC7nkw+e+RRk8mr2A==)

  security:
    user:
      name: ENC(1DWMT+U4oSOaV8qgepq6ZVrhcrBr2GT9+UNNM4+8PVgTsEIZOlIm7VvcMye7f1IS)
      password: ENC(jEeUwqRD0EULy1qETRiWRYBk+JeMJcJUb2GBd+VP3goCsIXfsAf7UWlvfmSk+cON)

  boot:
    admin:
      client:
        url: ${server.base-url}
        instance:
          prefer-ip: true
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
      ui:
        public-url: ${server.base-url}
        available-languages: ko
        view-settings:
          - name: wallboard
            enabled: false
          - name: journal
            enabled: false
        external-views:
          - label: "\uD638\uAC10\uB3C4"
            url: ${server.base-url}/favorite/list
            order: -9999
            iframe: true
          - label: "\uC5D1\uC140"
            url: https://docs.google.com/spreadsheets/d/1PKgmtFVrJWw4briZGxlfyKKUd3XaQscsmAGR6LZ12Os/edit?gid=1565504110#gid=1565504110
            order: -9998
            iframe: true

jasypt:
  encryptor:
    password: ${JASYPT_KEY}

google:
  spreadsheet:
    id: ENC(4hsMJwPVMud5uMCYlsY6AEofkUityI6pU68yrSgEnJHVsdG4bdFOcD6eWe08xkYIruy4deRX1xlIM+A5+lp47fVXaZqTZ8s5EwKzg63zpjU=)
    key: ${GOOGLE_PATH:src/main/resources/key/google_spread_sheet_key.json}

chzzk:
  channelId: ${CHZZK_CHANNEL:ENC(quG85YdX+oDu/vCBG0Aubp2vv0oNBCj2DGztfUIq58T/o9a4Bdd/YrCnDyE/GkhKZQw6ZaNqam0od0GQ+o2XcnetxVoX7PVqr+ogJ87sr4g=)}
  aut: ${CHZZK_AUT:ENC(jY3RrjnvOZxHTjxEYIoqDOQjJ53LXeXAMRtQpDZwZVVLA7uSFKmQPW7hsR+QjLoBZj0H9UKT+9qGFitNNQuqWItv0zrOrwg6DhoJNEmPClQPq2fDy3QF6cM1C2vdPC917EJy6aIuwInbW2yqbqJCCg==)}
  ses: ${CHZZK_SES:ENC(8GM+nyNy+27gKY9yAlZLJrJNaO0NbgMPt81dmZo3xn9u505GYaFObI37k2Dc7duqWqx9HbtNAJPsaTC0sU1heC/tqyOWTUybeA3rgm2n5TctrZg6PzJqjkK5NxcQYE3ZCTq38zCcNVoBk0H/qx//8Kaxw5/E3mqhkJLBS37iMgBZazXc59K6WeEOs3UAwm/MwsGgSaFKFEAj0GBIqqwhqAhRfAloKpZiBYyoHumd1y9aY+tblFQUrdYae9+lRycSLG7yjcnsvnUTTW0TA5MWQ9bLcIv5DSSVwstmLGJmBtC10Ld/I/N3vyIv1bBXTuADgHDd3lX1mdIvMVHKVyzU9dgDhyU0euQz14alCdTvXGJLmPwVsy6u8OFMSvoc6BqUJ5KXPVdmHmdd5BBhKAkTYZPhBHX5GtIkOKZCB0vFt9GlE+IavnZ0AYBsH2dwRFd4wgW7sC5Mz0wIiplX961FOyf2XZteOBcherOgaihKVa62otkGVMYuHaxOMrIPNMHuAnapGCKC64eye25qMgQn+GBNrdczMjDMr4XPL2M+hy7wYNuNa4dfJy4lE6DL4PQ2L0Ti5Yp0TPg7H9xBDzx2kWP4i0XQwroUiUfJEOg5mWvTcpJysiNvgKmcu8lHRKAyab+xe+IxLTToRc6YPWpXNOFkMwoATMJ4n8G/syl7qOXuuJ4DgNytmXJ+aV5AMVMxasa1Ib8DuZ4NfsK/1IIhZnn0jlspHcSg7WNIOPe7HSP+JoNVXEC2Eudc6rWxXz13)}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  file:
    path: /resources/logs
