name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.tag-check.outputs.tag_exists }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(awk -F'=' '/^version/ {gsub(/["'\''"]/, "", $2); print $2}' build.gradle | xargs)
          echo "::set-output name=version::$VERSION"

      - name: Check if version tag exists remotely
        id: tag-check
        run: |
          echo "Checking if tag ${{ steps.get_version.outputs.version }} exists in remote repository..."
          if git ls-remote --tags origin "refs/tags/${{ steps.get_version.outputs.version }}" | grep -q "${{ steps.get_version.outputs.version }}"; then
            echo "Version ${{ steps.get_version.outputs.version }} already exists. Skipping build and tag."
            echo "::set-output name=tag_exists::true"
          else
            echo "Version does not exist. Proceeding with build and tag."
            echo "::set-output name=tag_exists::false"
          fi

  build_and_tag:
    runs-on: ubuntu-latest
    needs: check_version
    if: ${{ needs.check_version.outputs.tag_exists == 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage --imageName ghcr.io/${{ github.repository }}:${{ needs.check_version.outputs.version }}

      - name: Create Tag
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ needs.check_version.outputs.version }}
          generate_release_notes: true

      - name: Tag Docker image with latest
        run: docker tag ghcr.io/${{ github.repository }}:${{ needs.check_version.outputs.version }} ghcr.io/${{ github.repository }}:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ needs.check_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}:latest
