name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get project version
        run: echo "VERSION=$(awk -F'=' '/^version/ {gsub(/["'\''"]/, "", $2); print $2}' build.gradle | xargs)" >> $GITHUB_ENV

      - name: Check if version tag exists
        run: |
          if git rev-parse "refs/tags/${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Version ${{ env.VERSION }} already exists. Exiting workflow."
            exit 0
          fi

      - name: Create Tag
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true

      - name: Build with Gradle
        run: |
         chmod +x gradlew
         ./gradlew bootBuildImage --imageName ghcr.io/${{ github.repository }}:${{ env.VERSION }}

      - name: Tag Docker image with latest
        run: docker tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} ghcr.io/${{ github.repository }}:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest